application: saj-textiles
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static
    
- url: /bootstrap/images
  static_files: images
  upload: /bootstrap/images/*

- url: .*
  script: main.app 
  
libraries:
- name: webapp2
  version: "latest"

  